[packages.linux.ubuntu.apt]
packages = [
    "bat",
    "curl",
    "man",
    "direnv",
    "fd-find",
    "ansible",
    "git-lfs",
    "jq",
    "ripgrep",
    "fzf",
    "fish",
    "htop",
    "just",
    "python3-dev",
    "python3-pip",
    "python3-setuptools",
    "virtualenvwrapper",
    "gdu",
    "tree",
    "units",
]

[packages.linux.ubuntu.snap]
packages = ["zellij", "nvim"]

[packages.linux.arch.common]
packages = [
    "bat",
    "vim",
    "whois",
    "sl",
    "w3m",
    "clang",
    "cmake",
    "expac",
    "chezmoi",
    "tree-sitter-cli",
    "rustup",
    "smartmontools",
    "7zip",
    "just",
    "curl",
    "starship",
    "direnv",
    "fd",
    "git-lfs",
    "inetutils",
    "zellij",
    "git",
    "eza",
    "go",
    "unzip",
    "wget",
    "git-delta",
    "jq",
    "fastfetch",
    "neovim",
    "fish",
    "github-cli",
    "ripgrep",
    "fzf",
    "htop",
    "python",
    "python-pip",
    "python-virtualenvwrapper",
    "python-setuptools",
    "python-pynvim",
    "gdu",
    "snap-pac",
    "zip",
    "tree",
    "lazygit",
    "bottom",
    "bc",
    "make",
    "gcc",
    "base-devel",
    "efibootmgr",
    "reflector",
    "openbsd-netcat",
    "pacman-contrib",
    "rsync",
    "imagemagick",
    "man-db",
    "dog",
    "nmap",
    "tailscale",
]
services = []

[packages.linux.arch.desktop]
packages = [
    "brightnessctl",
    "hyprland",
    "mpv",
    "aerc",
    "feh",
    "hyprcursor",
    "hypridle",
    "hyprlock",
    "hyprpicker",
    "hyprpolkitagent",
    "hyprshot",
    "hyprutils",
    "kanshi",
    "mako",
    "foot",
    "rofi",
    "rofi-calc",
    "ly",
    "firefox",
    "wl-clipboard",
    "wev",
    "maplemono-nf",
    "enpass-bin",
    "gvfs",
    "cpio",
    "gvfs-smb",
    "gvfs-nfs",
    "wireshark-qt",
    "obsidian",
    "rygel",
    "swaybg",
    "waybar",
    "seahorse",
    "gnome-keyring",
    "network-manager-applet",
    "networkmanager",
    "xdg-user-dirs-gtk",
    "xdg-utils",
    "xdg-desktop-portal-hyprland",
    "yt-dlp",
    "python-hyprpy",
    "zathura",
    "pcmanfm",
    "pipewire",
    "pipewire-alsa",
    "pipewire-jack",
    "pipewire-pulse",
    "libpulse",
    "wireplumber",
    "gst-plugin-pipewire",
    "pavucontrol",
    "wlr-randr",
    "zathura-pdf-mupdf",
]
services = ["ly@tty2.service"]

[packages.linux.arch.media]
packages = ["pocket-casts-linux-bin", "pinta"]
services = []

[packages.linux.arch.docker]
packages = ["docker", "docker-compose", "lazydocker"]
services = ["docker"]

[packages.linux.arch.wsl]
packages = ["win32yank-bin", "wsl-open"]
services = []

[packages.linux.arch.studywork]
packages = [
    "texlab",
    "typst",
    "glab",
    "miniforge",
    "python-eduvpn-client",
    "easyroam-desktop-bin",
    "rustdesk-bin",
    "xournalpp",
    "onlyoffice-bin",
    "zotero-bin",
]
services = []

[packages.linux.arch.mobile]
packages = [
    "tlp",
    "tlpui",
    "tlp-rdw",
    "powertop",
    "fwupd",
    "bluetui",
    "wireless_tools",
]
services = ["tlp"]

[packages.linux.arch.pentesting]
packages = [
    "gobuster",
    "exploitdb",
    "mitmproxy",
    "nmap",
    "mimikatz",
    "metasploit",
    "radare2",
    "iaito",
    "tcpdump",
    "wireshark-qt",

    "wpscan",
    "volatility3",
    "dirbuster",
    "burpsuite",
]
services = []

[packages.linux.fisher]
packages = [
    "jorgebucaran/fisher",
    "halostatue/fish-chezmoi",
    "patrickf1/fzf.fish",
    "nickeb96/puffer-fish",
    "jethrokuan/z",
    "edc/bass",
    "jorgebucaran/autopair.fish",
]

[packages.windows.winget]
packages = ["9N0DX20HK701"]

[packages.windows.scoop.pre]
packages = ["git"]

[packages.windows.scoop.desktop]
buckets = ["extras", "nerd-fonts"]
packages = [
    "7zip",
    "Maple-Mono-NF",
    "bat",
    "bottom",
    "cacert",
    "chezmoi",
    "curl",
    "dark",
    "delta",
    "fd",
    "ffmpeg",
    "fzf",
    "gdu",
    "gzip",
    "innounp",
    "lazygit",
    "less",
    "make",
    "enpass",
    "age",
    "neovim",
    "nodejs",
    "obsidian",
    "paint.net",
    "pandoc",
    "perl",
    "time",
    "powertoys",
    "pwsh",
    "python",
    "ripgrep",
    "ruby",
    "rufus",
    "rustup",
    "starship",
    "go",
    "sysinternals",
    "tree-sitter",
    "unzip",
    "wget",
    "winmerge",
    "openssl",
    "pdfarranger",
    "scc",
    "zig",
    "vlc",
]

[packages.windows.scoop.studywork]
buckets = ["java"]
packages = ["sumatrapdf", "zotero", "typst", "rustdesk", "xournalpp", "openjdk"]

[packages.windows.scoop.office]
buckets = []
packages = ["onlyoffice-desktopeditors", "thunderbird"]

[packages.windows.scoop.gaming]
buckets = ["games"]
packages = ["battlenet", "epic-games-launcher", "prismlauncher", "steam"]

[packages.go]
packages = [
    "github.com/burgr033/autoCommit@latest",
    "github.com/burgr033/t00lbox/cmd/t00lbox@latest",
]
