[packages.linux.ubuntu.apt]
packages = [
    "bat",
    "curl",
    "man",
    "direnv",
    "fd-find",
    "ansible",
    "git-lfs",
    "jq",
    "ripgrep",
    "fzf",
    "fish",
    "htop",
    "just",
    "python3-dev",
    "python3-pip",
    "python3-setuptools",
    "virtualenvwrapper",
    "gdu",
    "tree",
    "units",
]

[packages.linux.ubuntu.snap]
packages = ["zellij", "nvim"]

[packages.linux.arch.common]
packages = [
    "bat",
    "starship",
    "curl",
    "direnv",
    "fd",
    "man",
    "git-lfs",
    "inetutils",
    "zellij",
    "git",
    "eza",
    "go",
    "unzip",
    "git-delta",
    "jq",
    "fastfetch",
    "neovim",
    "fish",
    "github-cli",
    "ripgrep",
    "fzf",
    "htop",
    "python",
    "python-pip",
    "python-virtualenvwrapper",
    "python-setuptools",
    "python-pynvim",
    "gdu",
    "tree",
    "lazygit",
    "bottom",
    "bc",
    "make",
    "gcc",
    "base-devel",
    "efibootmgr",
    "reflector",
    "gnu-netcat",
    "pacman-contrib",
    "ranger",
    "imagemagick",
    "man-db",
    "dog",
    "nmap",
    "tailscale",
]

[packages.linux.arch.desktop]
packages = [
    "ghostty",
    "gdm",
    "gdm-settings",
    "firefox",
    "wl-clipboard",
    "wev",
    "maplemono-nf",
    "bibata-cursor-theme-bin",
    "enpass-bin",
    "gvfs",
    "gvfs-smb",
    "gtk-engine-murrine",
    "loupe",
    "gvfs-nfs",
    "wireshark-qt",
    "obsidian",
    "rygel",
    "snapshot",
    "tecla",
    "seahorse",
    "baobab",
    "celluloid",
    "checkupdates-with-aur",
    "gnome-backgrounds",
    "gnome-bluetooth",
    "gnome-browser-connector",
    "gnome-calculator",
    "gnome-calendar",
    "gnome-characters",
    "gnome-clocks",
    "gnome-color-manager",
    "gnome-connections",
    "gnome-contacts",
    "gnome-control-center",
    "gnome-disk-utility",
    "gnome-font-viewer",
    "gnome-keyring",
    "gnome-logs",
    "gnome-menus",
    "gnome-remote-desktop",
    "gnome-session",
    "gnome-settings-daemon",
    "gnome-shell",
    "gnome-shell-extensions",
    "gnome-system-monitor",
    "gnome-themes-extra",
    "gnome-tweaks",
    "gnome-user-docs",
    "gnome-user-share",
    "gnome-weather",
    "nautilus",
    "nautilus-open-any-terminal",
    "nautilus-share",
    "network-manager-applet",
    "networkmanager",
    "polkit-gnome",
    "xdg-desktop-portal-gnome",
    "xdg-user-dirs-gtk",
    "xdg-utils",
    "gnome-extensions-cli",
]
services = ["gdm"]


[packages.linux.arch.light_desktop]
packages = [
    "ghostty",
    "firefox",
    "wl-clipboard",
    "wev",
    "maplemono-nf",
    "enpass-bin",
    "wireshark-qt",
    "obsidian",
    "network-manager-applet",
    "networkmanager",
    "labwc",
    "ly",
]
services = ["ly"]


[packages.linux.arch.gnome_extensions]
extensions = [
    "windowIsReady_Remover@nunofarruca@gmail.com",
    "top-bar-organizer@julian.gse.jsts.xyz",
    "tailscale@joaophi.github.com",
    "nightthemeswitcher@romainvigier.fr",
    "mediacontrols@cliffniff.github.com",
    "date-menu-formatter@marcinjakubowski.github.com",
    "dash-to-dock@micxgx.gmail.com",
    "caffeine@patapon.info",
    "Bluetooth-Battery-Meter@maniacx.github.com",
    "arch-update@RaphaelRochet",
    "appindicatorsupport@rgcjonas.gmail.com",
    "app-hider@lynith.dev",
]

[packages.linux.arch.virtualization]
packages = ["gnome-boxes"]

[packages.linux.arch.media]
packages = ["pocket-casts-linux-bin"]

[packages.linux.arch.comms]
packages = ["signal-desktop", "fractal", "discord"]

[packages.linux.arch.studywork]
packages = [
    "texlab",
    "typst",
    "glab",
    "glim",
    "tectonic",
    "easyroam-desktop-bin",
    "rustdesk-bin",
    "xournalpp",
    "thunderbird",
    "onlyoffice-bin",
    "zotero-bin",
]

[packages.linux.arch.virtualguest]
packages = ["spice-vdagent"]
services = ["spice-vdagent"]

[packages.linux.arch.opensnitch]
packages = ["opensnitch-ebpf-module", "opensnitch-git"]
services = ["opensnitchd"]

[packages.linux.arch.pentesting]
packages = [
    "gobuster",
    "exploitdb",
    "mitmproxy",
    "nmap",
    "mimikatz",
    "metasploit",
    "radare2",
    "iaito",
    "tcpdump",
    "wireshark-qt",
    "wpscan",
    "volatility3",
    "dirbuster",
    "burpsuite",
]
[packages.linux.fisher]
packages = [
    "jorgebucaran/fisher",
    "halostatue/fish-chezmoi",
    "patrickf1/fzf.fish",
    "nickeb96/puffer-fish",
    "jethrokuan/z",
    "edc/bass",
    "jorgebucaran/autopair.fish",
]

[packages.windows.winget]
packages = ["9N0DX20HK701"]


[packages.windows.scoop.pre]
packages = ["git"]

[packages.windows.scoop.desktop]
buckets = ["extras", "nerd-fonts"]
packages = [
    "7zip",
    "Maple-Mono-NF",
    "bat",
    "bottom",
    "cacert",
    "chezmoi",
    "curl",
    "dark",
    "delta",
    "fd",
    "ffmpeg",
    "fzf",
    "gdu",
    "gzip",
    "innounp",
    "lazygit",
    "less",
    "make",
    "enpass",
    "age",
    "neovim",
    "nodejs",
    "obsidian",
    "paint.net",
    "pandoc",
    "perl",
    "time",
    "powertoys",
    "pwsh",
    "python",
    "ripgrep",
    "ruby",
    "rufus",
    "rustup",
    "starship",
    "go",
    "sysinternals",
    "tree-sitter",
    "unzip",
    "wget",
    "winmerge",
    "openssl",
    "pdfarranger",
    "scc",
    "zig",
    "vlc",
]

[packages.windows.scoop.studywork]
buckets = ["java"]
packages = [
    "sumatrapdf",
    "zotero",
    "texlab",
    "tectonic",
    "typst",
    "rustdesk",
    "xournalpp",
    "openjdk",
]

[packages.windows.scoop.office]
buckets = []
packages = ["onlyoffice-desktopeditors", "thunderbird"]


[packages.windows.scoop.gaming]
buckets = ["games"]
packages = ["battlenet", "epic-games-launcher", "prismlauncher", "steam"]

[packages.go]
packages = [
    "github.com/burgr033/autoCommit@latest",
    "github.com/burgr033/t00lbox/cmd/t00lbox@latest",
]
